routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('home');
});

// Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/home', 'HomeController@redirectionAfficheCombat');
Route::get('/player/{combatant}', 'HomeController@afficheCombatant')->name('affiche_combatant');
Route::get('/Combat/{premier_combatant}/vs/{dexieme_combatant}', 'HomeController@afficheCombat')->name('affiche_combat');
Route::get('dowload-img/{combatant}','HomeController@showJqueryImageUpload')->name('upload-img-combatant');
Route::post('dowload-img','HomeController@saveJqueryImageUpload')->name('upload-img');
Route::resource('/gestion_combatants','GestionCombatants');

app/Models/Categorie.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Categorie extends Model
{
    protected $primaryKey = 'idcategories';
    
}

app/Models/Combatant.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Combatant extends Model
{
    protected $primaryKey = 'idcombatants';
     protected $fillable = [
        'nom','postnom','prenom','idcategories','poid'
    ];
    public $timestamps = false;


    /**********
    * SCOPES 
    **********/

    /**
    * Joindre categorie 
    */

    public static function scopeJoinCategorie($query){

     return $query->leftJoin('categories', 'categories.idcategories', '=', 'combatants.idcategories');

    }



    
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/GestionCombatants.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\DataTables\GestionCombatantDataTable;
use App\Models\Combatant;
use Flashy;

class GestionCombatants extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(GestionCombatantDataTable $dataTables)
    {
        return $dataTables->render('gestion_combatants');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $combatant = Combatant::create($request->all());
        Flashy::info('Ajouter une photo de profil pour ' .$combatant->nom);
        return redirect()->route('upload-img-combatant',$combatant->idcombatants);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        Combatant::destroy($id);
        Flashy::error('Supprimé avec succèss');
        return redirect()->back();


    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        dd('Bil');
        Combatant::destroy($id);
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Combatant;
use App\Http\Requests\AfficheCombatRequest;
use Validator;


class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        // $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $combatants = Combatant::JoinCategorie()->get();
        return view('home',compact('combatants'));
    }


    public function redirectionAfficheCombat(AfficheCombatRequest $request)
    {
        return redirect()->route('affiche_combat',[$request->premier_combatant,$request->dexieme_combatant]);
    }

    public function afficheCombatant(Combatant $combatant)
    {
        $combatant = Combatant::JoinCategorie()->find($combatant->idcombatants);
       
        return view('affiche_combatant',compact('combatant'));
    }

     public function afficheCombat(Combatant $premier_combatant,Combatant $dexieme_combatant)
    {
        $premier_combatant = Combatant::JoinCategorie()->find($premier_combatant->idcombatants);
        $dexieme_combatant = Combatant::JoinCategorie()->find($dexieme_combatant->idcombatants);
        // dump($premier_combatant);
        // dd($dexieme_combatant);
        return view('affiche_combat',compact('premier_combatant','dexieme_combatant'));
    }

    // UPLOAD IMG


    public function showJqueryImageUpload(Combatant $combatant) 
    {
        return view('uploade',compact('combatant'));
    }

    /**
     * To handle the comming post request
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function saveJqueryImageUpload(Request $request)
    {
        
        $validator = Validator::make($request->all(), [
            'profile_picture' => 'required|image|max:1000',
            'idcombatants' => 'required|exists:combatants',
        ]);
        if ($validator->fails()) {
            
            return $validator->errors();            
        }


        $status = "";

        if ($request->hasFile('profile_picture')) {
            $image = $request->file('profile_picture');
            // Rename image
            $filename = time().'.'.$image->guessExtension();
            
            $path = $request->file('profile_picture')->storeAs(
                 'profile_pictures', $filename
            );
            $combatant = Combatant::find($request->idcombatants);
            $combatant->picture = $path;
            $combatant->save();
            $status = "uploaded";            
        }
        
        return response($status,200);
    }

}

resources/views/affiche_combat.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="Bil Wifi" content="{{ config('app.name') }} by KinDev">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href={{ asset('favicon.ico') }}>
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ !empty ($title) ? $title .' | '. config('app.name') : config('app.name') }}  </title>

    @yield('stylesheet1')
        <!-- Custom CSS -->
    <link href="{{ asset('backend/dist/css/style.min.css') }}" rel="stylesheet">
     <link href="{{ asset('dataTables/dataTables/css/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
    <link href="{{ asset('dataTables/buttons/css/buttons.dataTables.min.css') }}" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Custom styles for this template -->
    <style type="text/css">
        html,
        body {
          overflow-x: hidden; /* Prevent scroll on narrow devices */
        }

        body {
          /*padding-top: 56px;*/
        }

        @media (max-width: 991.98px) {
          .offcanvas-collapse {
            position: fixed;
            top: 56px; /* Height of navbar */
            bottom: 0;
            left: 100%;
            width: 100%;
            padding-right: 1rem;
            padding-left: 1rem;
            overflow-y: auto;
            visibility: hidden;
            background-color: #343a40;
            transition-timing-function: ease-in-out;
            transition-duration: .3s;
            transition-property: left, visibility;
          }
          .offcanvas-collapse.open {
            left: 0;
            visibility: visible;
          }
        }

        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }

        .nav-scroller .nav {
          display: -ms-flexbox;
          display: flex;
          -ms-flex-wrap: nowrap;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          color: rgba(255, 255, 255, .75);
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }

        .nav-underline .nav-link {
          padding-top: .75rem;
          padding-bottom: .75rem;
          font-size: .875rem;
          color: #6c757d;
        }

        .nav-underline .nav-link:hover {
          color: #007bff;
        }

        .nav-underline .active {
          font-weight: 500;
          color: #343a40;
        }

        .text-white-50 { color: rgba(255, 255, 255, .5); }

        .bg-purple { background-color: #6f42c1; }

        .lh-100 { line-height: 1; }
        .lh-125 { line-height: 1.25; }
        .lh-150 { line-height: 1.5; }
    </style>
    <style type="text/css">
      .affiche-img{
        border-radius: 50% !important;
        height: 50%;
      }
      .affiche-img-panel{
        display: fixed;  
        height: 50%;
      }
      .dx-c{
        display: fixed;  
        align-items: right;
        margin-left: 50
      }
    </style>
  </head>

  <body class="bg-light">


    <main role="main" class="container-fluid">
      <div class="">
        <div class="row">
          <div class="col-5 d-flex align-items-center p-3 my-3 text-white-50 bg-purple rounded shadow-sm" style="height: 120px">
            <img class="mr-3" src="{{ url(Storage::url($premier_combatant->picture)) }}" alt="" width="75" height="75">
            <div class="lh-100">
              <h1 class="mb-0 text-white lh-100">
                {{ $premier_combatant->nom .' '.$premier_combatant->prenom  }}
              </h1>
              <br>
              <small>Poid : {{ $premier_combatant->poid  }}Kg</small><br>
              <small>Catégorie : {{ $premier_combatant->lib  }}</small>
            </div>
          </div>
          <div class="col-2 d-flex justify-content-center align-items-center"><h1>VS</h1></div>
          <div class="col-5  d-flex flex-row-reverse align-items-center p-3 my-3 text-white-50 bg-purple rounded shadow-sm" style="height: 120px">
            <img class="mr-3" src="{{ url(Storage::url($dexieme_combatant->picture)) }}" alt="" width="75" height="75" style="margin-left: 3%">

            <div class="lh-100 " style="align-content: right; align-items: right;">
              <h1 class="mb-0 text-white lh-100">
                {{ $dexieme_combatant->nom .' '.$dexieme_combatant->prenom  }}
              </h1>
              <br>
              <small class="float-right">Poid : {{ $dexieme_combatant->poid  }}Kg</small><br>
              <small class="float-right">Catégorie : {{ $dexieme_combatant->lib  }}</small>
            </div>
          </div>
        </div>
        
      </div>

      <div class=" ">
        {{-- CONTENT --}}
        <div class="affiche-panel row">
          <div class="col-5 ">
            <div class="affiche-content">
              <div class="affiche-img-panel">
                <img src="{{ url(Storage::url($premier_combatant->picture)) }}" class="affiche-img img-fluid" width="500" height="500">
              </div> 
            </div>
          </div>
          <div class="col-2"></div>
          <div class="col-5">
            <div class="affiche-content">
              <div class="affiche-img-panel">
                <img src="{{ url(Storage::url($dexieme_combatant->picture)) }}" class="affiche-img img-fluid" width="500" height="500">
              </div> 
            </div>
          </div>
        </div>

      </div>

      
    </main>

    <script src={{ asset('backend/assets/libs/jquery/dist/jquery.min.js') }}></script>
    <script src={{ asset('js/jsDiscret.js') }}></script>
    <!-- <script src="dist/js/jquery.ui.touch-punch-improved.js"></script>
    <script src="dist/js/jquery-ui.min.js"></script> -->
    <!-- Bootstrap tether Core JavaScript -->
    <script src={{ asset('backend/assets/libs/popper.js/dist/umd/popper.min.js') }}></script>
    <script src={{ asset('backend/assets/libs/bootstrap/dist/js/bootstrap.min.js') }}></script>
     <script type="text/javascript" src="{{ asset('dataTables/datatables.min.js') }}"></script>
     @stack('scripts')

  </body>

<!-- Mirrored from getbootstrap.com/docs/4.1/examples/floating-labels/ by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 07 Nov 2018 23:42:06 GMT -->
</html>

resources/views/gestion_combatants.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
	<div class="create">
		<button type="button" class="addModal btn btn-info" data-toggle="modal" data-target="#editModal">
	  		 <span class="fa fa-plus"> </span> Ajouter
		</button>
	</div>
	<br>
	<div class="card ">
		<div class="card-body fluid">
			{!!$dataTable->table() !!}	
		</div>
	</div>
</div>

<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Ajouter</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        {{-- Formulaire --}}
        <form method="POST" action="{{ route('gestion_combatants.store') }}" class="form-horizontal">
            @csrf
           <input type="hidden" name="idetudiants" id="fidetudiants" >
            <div class="form-group">
                <label for="nom"  class="col-sm-2 control-label">Nom</label>
                <div class="col-sm-12">
                    <input type="text" id="fnom" class="form-control" id="nom" name="nom" placeholder="Entrer nom combatant"  maxlength="50" required="">
                </div>
            </div>
            <div class="form-group">
                <label for="postnom" class="col-sm-2 control-label">Postnom</label>
                <div class="col-sm-12">
                    <input type="text" id="fpostnom" class="form-control" id="postnom" name="postnom" placeholder="Entrer postnom combatant"  maxlength="50" >
                </div>
            </div>
            <div class="form-group">
                <label for="prenom"  class="col-sm-2 control-label">Prenom</label>
                <div class="col-sm-12">
                    <input type="text" id="fprenom" class="form-control" id="prenom" name="prenom" placeholder="Entrer prenom combatant"  maxlength="50" required="">
                </div>
            </div>
              <div class="form-group">
                  <label class="col-sm-2 control-label">Categorie</label>
                  <div class="col-sm-12">
                      
                    <select class="form-control" id="fidcategorie" name="idcategories" required="">
                          @foreach(App\Models\Categorie::get() as $cat)
                              <option value="{{ $cat->idcategories }}"  >{{ $cat->lib }} ({{ $cat->poid_min.'Kg - '.$cat->poid_max.'Kg' }})</option>
                          @endforeach
                    </select>
                  </div>
              </div> 
              <div class="form-group">
                <label for="poid"  class="col-sm-2 control-label">Poid</label>
                <div class="col-sm-12">
                    <input type="number" id="fpoid" class="form-control" id="poid" name="poid" placeholder="Entrer le poid "  maxlength="50" >
                </div>
              </div>        
	      <div class="modal-footer">
	        <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
	        <button type="submit" class="save btn btn-primary">Enregistrer</button>
	      </div>
        </form>
      </div>
    </div>
  </div>
</div>

@endsection
@push('scripts')
{!!$dataTable->scripts() !!}

@endpush









@push('stylesheets')
    <link href="{{ asset('dataTables/dataTables/css/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endpush

@section('script')

<script src={{ asset('dataTables/datatables.min.js') }}></script> 

@endsection

resources/views/layouts/master.blade.php
<!doctype html>
<html lang="en">
  
<!-- Mirrored from getbootstrap.com/docs/4.1/examples/starter-template/ by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 07 Nov 2018 23:41:57 GMT -->
<meta http-equiv="content-type" content="text/html;charset=utf-8" /><!-- /Added by HTTrack -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="Bil Wifi" content="{{ config('app.name') }} by KinDev">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href={{ asset('favicon.ico') }}>
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ !empty ($title) ? $title .' | '. config('app.name') : config('app.name') }}  </title>

    @yield('stylesheet1')
        <!-- Custom CSS -->
    <link href="{{ asset('bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/dashboard.css') }}" rel="stylesheet">
    <link href="{{ asset('bootstrap/icons/font-awesome/css/fontawesome-all.css') }}" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style type="text/css">
      body {
              padding-top: 5rem;
            }
            .starter-template {
              padding: 3rem 1.5rem;
              text-align: center;
            }
    </style>
    @yield('stylesheet')
    <!-- Coustom styleSheet--->
    @stack('stylesheets')


</head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      {{-- <a class="navbar-brand" href="#">Navbar</a> --}}
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{{ route('home') }}">Acceuil <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{{ route('gestion_combatants.index') }}">Combattants <span class="sr-only">(current)</span></a>
          </li>
        </ul>
        {{-- <div class="my-2 my-lg-0">
          <button class="btn btn-outline-danger my-2 my-sm-0">Déconnexion</button>
        </div> --}}
      </div>
    </nav>

    
    <div class="content">
      @yield('content')
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
{{--     <script src="../../assets/js/vendor/jquery-slim.min.js" ></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
  </body> --}}

    <script src={{ asset('backend/assets/libs/jquery/dist/jquery.min.js') }}></script>

      <!-- BOOTSTRAP SCRIPTS -->
    <script src={{ asset('backend/assets/libs/bootstrap/dist/js/bootstrap.min.js') }}></script>
    <script src={{ asset('bootstrap/js/bootstrap.bundle.min.js') }}></script>
    <script src={{ asset('js/popper.min.js') }}></script>
    @yield('script')
    @stack('scripts')
    @include('flashy::message')
    
  </body>

<!-- Mirrored from getbootstrap.com/docs/4.1/examples/cover/ by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 07 Nov 2018 23:41:49 GMT -->

</html>

resources/views/uploade.blade.php
@extends('layouts.master')

@section('stylesheet')


<!-- Croppie css -->
<link rel="stylesheet" type="text/css" 
    href="{{ asset('css/cropie.css') }}">
<!-- Font Awesome 5 -->



<style type="text/css">
.nounderline, .violet{
    color: #7c4dff !important;
}
.btn-dark {
    background-color: #7c4dff !important;
    border-color: #7c4dff !important;
}
.btn-dark .file-upload {
    width: 100%;
    padding: 10px 0px;
    position: absolute;
    left: 0;
    opacity: 0;
    cursor: pointer;
}
.profile-img img{
    width: 200px;
    height: 200px;
    border-radius: 50%;
}    
</style>

@endsection

@section('content')
<p>&nbsp;</p>
<div  class="container"> 
        
    <h3 class="text-center mb-5">
    Ajouter une image de profil pour le combantant
    </h3>

    <div class="d-flex justify-content-center p-3">
        <div class="card text-center">
            <div class="card-body">
                <h5 class="card-title">Uploader une image</h5>
                <div class="profile-img p-3">
                    <img src="{{ asset('img/img-profil.png') }}" id="profile-pic">
                </div>
                <div class="btn btn-dark">
                    <input type="file" class="file-upload" id="file-upload" 
                    name="profile_picture" accept="image/*">
                    Sélectionner une image 
                </div>
            </div>
        </div>
    </div>

    <!-- The Modal -->
    <div class="modal" id="myModal">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Crop Image And Upload</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <!-- Modal body -->
                <div class="modal-body">
                    <div id="resizer"></div>
                    <button class="btn rotate float-lef" data-deg="90" > 
                    <i class="fas fa-undo"></i></button>
                    <button class="btn rotate float-right" data-deg="-90" > 
                    <i class="fas fa-redo"></i></button>
                    <hr>
                    <button class="btn btn-block btn-dark" id="upload" > 
                    Crop And Upload</button>
                </div>
            </div>
        </div>
    </div>


</div>
    
@stop

@push('scripts')




<!-- Croppie js -->
<script src="{{ asset('js/cropie.js') }}"></script>

<script type="text/javascript">
 $(function() {
    var croppie = null;
    var el = document.getElementById('resizer');

    $.base64ImageToBlob = function(str) {
        // extract content type and base64 payload from original string
        var pos = str.indexOf(';base64,');
        var type = str.substring(5, pos);
        var b64 = str.substr(pos + 8);
      
        // decode base64
        var imageContent = atob(b64);
      
        // create an ArrayBuffer and a view (as unsigned 8-bit)
        var buffer = new ArrayBuffer(imageContent.length);
        var view = new Uint8Array(buffer);
      
        // fill the view, using the decoded base64
        for (var n = 0; n < imageContent.length; n++) {
          view[n] = imageContent.charCodeAt(n);
        }
      
        // convert ArrayBuffer to Blob
        var blob = new Blob([buffer], { type: type });
      
        return blob;
    }

    $.getImage = function(input, croppie) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function(e) {  
                croppie.bind({
                    url: e.target.result,
                });
            }
            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#file-upload").on("change", function(event) {
        $("#myModal").modal();
        // Initailize croppie instance and assign it to global variable
        croppie = new Croppie(el, {
                viewport: {
                    width: 200,
                    height: 200,
                    type: 'circle'
                },
                boundary: {
                    width: 250,
                    height: 250
                },
                enableOrientation: true
            });
        $.getImage(event.target, croppie); 
    });

    $("#upload").on("click", function() {
        croppie.result('base64').then(function(base64) {
            $("#myModal").modal("hide"); 
            $("#profile-pic").attr("src","/images/ajax-loader.gif");

            var url = "{{ route('upload-img') }}";
            var formData = new FormData();
            formData.append("profile_picture", $.base64ImageToBlob(base64));
            formData.append("idcombatants", "{{ $combatant->idcombatants }}");

            // This step is only needed if you are using Laravel
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            $.ajax({
                type: 'POST',
                url: url,
                data: formData,
                processData: false,
                contentType: false,
                success: function(data) {
                    if (data == "uploaded") {
                       return location = "{{ route('gestion_combatants.index') }}" ;
                    } else {
                        $("#profile-pic").attr("src","/images/icon-cam.png"); 
                        console.log(data['profile_picture']);
                    }
                },
                error: function(error) {
                    console.log(error);
                    $("#profile-pic").attr("src","/images/icon-cam.png"); 
                }
            });
        });
    });

    // To Rotate Image Left or Right
    $(".rotate").on("click", function() {
        croppie.rotate(parseInt($(this).data('deg'))); 
    });

    $('#myModal').on('hidden.bs.modal', function (e) {
        // This function will call immediately after model close
        // To ensure that old croppie instance is destroyed on every model close
        setTimeout(function() { croppie.destroy(); }, 100);
    })

}); 
</script>
    
@endpush